appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Aph0phhIXCEuwJhQvQQghEPBgRPHB/4bDTiLlOI3MLVnnveJfGQTQBGo/cKkJJiVh3raiB+4Dnx07i9YBOUoH5X6pGXhA6tcBDzfAllCoUcRm2nac/XVmp6gmYyj2ep5GNVybXUH4I+z+DI2Q3eX929yf5Y655UmyUwDAWeObRw+r1EbhwwITYCi3tzVlGoGQp3G3ZMdOxR6eRe0xWhyd8gcupIRzHnW+TqdTFmgsAPtjwOiENCTEHyP9jr4XlrOPp9nKdGHVgXzWjtYBffAHBh6p/zTP2yMOp0M2wlNXXEubqj7TrT5FBT0WWDi+9KiXm6bo7haOEmLkeBB50KFT2YbUspkBU0t+xuAJh0A0tQEUpG7saMuJRj5DYPFwCzf9e8YFp0Nh/9/6i121BDuUnMih6vFk7t78T3ixvWcK8+9D7PsNJGn3fR8iJBrnum7bN5zsxFYq+3x26U8mweZVVkdslxp3MLQ4XFEiwX6qfZMkKHOzF+4QsMdc/3k+WGm8F0FeUQKHz4rySpEmfefBN/PguRUqDPpZvPU2a2QqTY+9s315l2xrftr5aX5w/auXUDz6a9FWdf0vpPvVusP9qqSMZDRrShcl0Is3Vj50A54A6+L4lPOvEAQVajYbUMmxAy5qlPSZVFHCA7uSA5kxAw6feq/5uHkgI6PCC0vE7c=}
bot:
  automerge: true
conda_forge_output_validation: true
